# Generated by Django 5.0 on 2025-11-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("iso_standard", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("in_progress", "En Progreso"),
                            ("completed", "Completada"),
                            ("approved", "Aprobada"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("observations", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Auditoría",
                "verbose_name_plural": "Auditorías",
                "db_table": "audits",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
    ]
