# Generated by Django 5.0 on 2025-11-16 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "audit_sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AuditTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("iso_standard", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "audit_templates",
            },
        ),
        migrations.AlterModelOptions(
            name="audit",
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AuditQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "answer_type",
                    models.CharField(
                        choices=[
                            ("yes_no", "Sí/No"),
                            ("yes_no_partial", "Sí/No/Parcial"),
                            ("scale_1_5", "Escala 1-5"),
                            ("text", "Texto"),
                        ],
                        default="yes_no_partial",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="audits.auditsection",
                    ),
                ),
            ],
            options={
                "db_table": "audit_questions",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="auditsection",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="audits.audittemplate",
            ),
        ),
        migrations.CreateModel(
            name="AuditResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(blank=True)),
                ("answer_choice", models.CharField(blank=True, max_length=20)),
                ("answer_numeric", models.IntegerField(blank=True, null=True)),
                ("evidence_file", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="audits.audit",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audits.auditquestion",
                    ),
                ),
            ],
            options={
                "db_table": "audit_responses",
                "unique_together": {("audit", "question")},
            },
        ),
    ]
