# Generated by Django 5.0 on 2025-12-02 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audits", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audits",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="auditresponse",
            name="audit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="audits.audit",
            ),
        ),
        migrations.AddField(
            model_name="auditresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="audits.auditquestion"
            ),
        ),
        migrations.AddField(
            model_name="auditquestion",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="audits.auditsection",
            ),
        ),
        migrations.AddField(
            model_name="auditsection",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="audits.audittemplate",
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="audits.audittemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="auditresponse",
            unique_together={("audit", "question")},
        ),
    ]
